# ===============================
# Server Configuration
# ===============================
server.port=8080
spring.application.name=ecommerce

# ===============================
# Database Configuration
# ===============================
# Replace 'localhost' with your specific IP address if connecting to a remote server
spring.datasource.url=jdbc:mysql://localhost:3306/ecom?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Yangon
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ===============================
# Swagger UI Configuration
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# ===============================
# JWT Configuration
# ===============================
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# File Upload Directory configuration
file.upload-dir=uploads/product-images


# Spring Multipart configuration 
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

file.upload-dir=./uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

#mmspg
payment.gateway.base-url=http://localhost:8004/api/v1
payment.gateway.client-id=mms_test_be4342691bd347d4
payment.gateway.client-secret=i3aupbhPQKvO4hIthG70AwhscQ71rSpXGE_hfDPqwes
payment.gateway.branch-id=01a11aa3-311f-73ce-b737-80ca972f799d

